volumes:
  auth_service_db:
  certs:

services:
  auth_service_db:
    image: postgres:15
    container_name: auth_service_db
    env_file: ../example.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - auth_service_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile
      target: production
    container_name: auth_service
    env_file: ../example.env
    depends_on:
      auth_service_db:
        condition: service_healthy
    volumes:
      - certs:/certs
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:8000/api/v1/healthcheck || exit 1"]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 10s

  tests:
    build:
      context: .. 
      dockerfile: infra/Dockerfile
      target: test
    container_name: auth_service_tests
    volumes:
      - .:/app
    profiles: ["test"]
