volumes:
  pg_data:
  src:
  certs:

services:
  db:
    container_name: auth_service_db
    image: postgres:15
    env_file: ../example.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    container_name: auth_service
    build: ./
    ports:
      - 8000:8000
    command: /bin/bash ./entrypoint.sh
    env_file: ../example.env
    depends_on:
      - db
    volumes:
      - ../src:/src
      - ../certs:/certs